Only use results from GetWindowProperty if it returned success
Since Xlib prior to 1.6 didn't always clear values on failure, don't
assume they're safe to use unless we succeeded.

Reported by Oracle Parfait 1.5.1:
Error: Uninitialised memory (CWE 456)
   Possible access to uninitialised memory '&nPixels'
        at line 963 of src/parse.c in function 'put_pixel_on_root'.
          &nPixels allocated at line 953.
   Possible access to uninitialised memory '&retProp'
        at line 962 of src/parse.c in function 'put_pixel_on_root'.
          &retProp allocated at line 954.

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>